- hosts: lhs2
  vars:
   - userName: libesz
   - userEmail: huszty.gergo@digitaltrip.hu
  tasks:
   - name: Install basic backages
     become: yes
     action: apt pkg={{item}} state=installed update_cache=true
     with_items:
       - vim
       - htop
       - aptitude
       - mc
       - git
       - zsh

   - name: Apply .vimrc
     become_user: "{{userName}}"
     copy: dest=~/.vimrc src=./to_copy/.vimrc owner={{userName}} group={{userName}}

   - name: Get current shell
     shell: 'cat /etc/passwd | grep {{userName}} | cut -d: -f 7'
     register: current_shell

   - name: Check oh-my-zsh
     stat: path=/home{{userName}}/.oh-my-zsh
     register: oh_my_zsh_installed

   - name: Change shell to zsh
     become: yes
     when: current_shell.stdout != '/bin/zsh'
     shell: chsh -s /bin/zsh {{userName}}

   - name: Configure git email
     become_user: "{{userName}}"
     git_config: name=user.email value={{userEmail}} scope=global

   - name: Configure git user
     become_user: "{{userName}}"
     git_config: name=user.name value={{userName}} scope=global

   - name: Get oh-my-zsh
     become_user: "{{userName}}"
     when: oh_my_zsh_installed.stat.exists != False
     shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
