- hosts: lhs2
  vars:
   - userName: libesz
   - userEmail: huszty.gergo@digitaltrip.hu
  tasks:
   - name: Install VIM
     become: yes
     apt: pkg=vim state=installed update_cache=true
     register: vimInstalled

   - name: Apply .vimrc
     when: vimInstalled|success
     become_user: "{{userName}}"
     copy: dest=~/.vimrc src=./to_copy/.vimrc owner={{userName}} group={{userName}}

   - name: Install htop
     become: yes
     apt: pkg=htop state=installed update_cache=true

   - name: Install aptitude
     become: yes
     apt: pkg=aptitude state=installed update_cache=true

   - name: Install mc
     become: yes
     apt: pkg=mc state=installed update_cache=true

   - name: Install zsh
     become: yes
     apt: pkg=zsh state=installed update_cache=true
     register: zshInstalled

   - name: Change shell to zsh
     when: zshInstalled
     register: changedShellToZsh
     become: yes
     shell: chsh -s /bin/zsh {{userName}}

   - name: Install git
     apt: pkg=git state=installed update_cache=true
     become: yes
     register: gitInstalled

   - name: Configure git
     when: gitInstalled|success
     become_user: "{{userName}}"
     shell: git config --global user.name {{userName}}; \
            git config --global user.email {{userEmail}}

   - name: Get oh-my-zsh
     when: (gitInstalled|success and changedShellToZsh|success)
     become_user: "{{userName}}"
     shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
