- hosts: lhs
  vars:
    - userName: <REPLACE_ME>
    - userEmail: <REPLACE_ME>
    - downloadLocation: <REPLACE_ME>
    - lanNicName: lan0
    - wanNicName: wan0
  roles:
    - basic_packages
    - router
    - role: dyndns
      dnsScriptPath: /usr/bin/dnsupdate.sh
      dnsUpdateUrl: http://freedns.afraid.org/dynamic/update.php?<REPLACE_ME>
    - role: munin
      muninEscapedExtServer: <REPLACE ME>
    - docker
    - startup
    - role: rtorrent
      rtorrentUser: <REPLACE_ME>
      rtorrentPass: <REPLACE_ME>
    - role: samba
      sambaWebShareLocation: <REPLACE_ME>
      sambaUtilShareLocation: <REPLACE_ME>
      sambaOtherShareLocation: <REPLACE_ME>
      sambaPicturesShareLocation: <REPLACE_ME>
    - minidlna
    - role: nginx
      fqdn: '<REPLACE ME>'
      piLanIp: '<REPLACE ME>'
    - role: gitolite
      pubKeyForGitolite: "<REPLACE ME>"
      repoRootPath: "<REPLACE_ME>"
