- hosts: lhs
  vars:
    - userName: <REPLACE_ME>
    - userEmail: <REPLACE_ME>
    - downloadLocation: <REPLACE_ME>
    - lanNicName: lan0
    - wanNicName: wan0
    - lanIP: <REPLACE_ME>
  roles:
    - basic_packages
    - role: router
      lanDevices:
        - name: <REPLACE_ME>
          mac: <REPLACE_ME>
          ip: <REPLACE_ME>
          exposeTCP:
            - from: <REPLACE_ME>
              to: <REPLACE_ME>
    - role: apcups
      upsSerial: "<REPLACE_ME>"
    - role: dyndns
      dnsScriptPath: /usr/bin/dnsupdate.sh
      dnsUpdateUrl: http://freedns.afraid.org/dynamic/update.php?<REPLACE_ME>
    - role: munin
      muninEscapedExtServer: <REPLACE ME>
    - role: docker
      dataRoot: <REPLACE_ME>
    - startup
    - role: rtorrent
      rtorrentUser: <REPLACE_ME>
      rtorrentPass: <REPLACE_ME>
    - role: samba
      sambaWebShareLocation: <REPLACE_ME>
      sambaUtilShareLocation: <REPLACE_ME>
      sambaOtherShareLocation: <REPLACE_ME>
      sambaPicturesShareLocation: <REPLACE_ME>
    - minidlna
    - role: nextcloud
      dbPassword: <REPLACE_ME>
    - role: nginx
      fqdn: '<REPLACE ME>'
      piLanIp: '<REPLACE ME>'
      pi2LanIp: '<REPLACE_ME>'
    - role: gitolite
      pubKeyForGitolite: "<REPLACE ME>"
      repoRootPath: "<REPLACE_ME>"
