- hosts: lhs2
  tasks:
   - name: Install web server related packages
     become: yes
     action: apt pkg={{item}} state=installed update_cache=true
     with_items:
       - nginx
       - php5
       - php5-fpm
       - php5-cgi

   - name: Configure nginx
     become: yes
     copy: dest=/etc/nginx/nginx.conf src=./to_copy/nginx.conf

   - name: Configure php5-fpm
     become: yes
     register: php5FpmConfigured
     replace: dest=/etc/php5/fpm/pool.d/www.conf regexp='(\s+)listen = /var/run/php5-fpm.sock$' replace='\1listen = 127.0.0.1:9000' backup=yes

   - name: Copy test php page
     become: yes
     copy: dest=/var/www/html/test.php src=./to_copy/test.php
     notify:
       - Start and enable php5-fpm
       - Start and enable nginx

  handlers:
   - name: Start and enable php5-fpm
     become: yes
     service: name=php5-fpm state=restarted enabled=yes

   - name: Start and enable nginx
     become: yes
     service: name=nginx state=restarted enabled=yes
