- name: Create downloads directory
  become: yes
  file: path={{downloadLocation}} state=directory owner={{userName}}

- name: Create downloads temp directory
  become: yes
  file: path={{downloadLocation}}_notready state=directory owner={{userName}}

- name: Create password auth for webui
  shell: echo "{{rtorrentUser}}:$(openssl passwd -crypt {{rtorrentPass}})" > {{downloadLocation}}/.htpasswd

- name: Create rtorrent docker-compose directory
  file: path=/home/{{userName}}/docker/rtorrent state=directory

- name: Create rtorrent docker-compose yml
  template: src=docker-compose.yml.j2 dest=/home/{{userName}}/docker/rtorrent/docker-compose.yml

- name: Create rtorrent service
  command: docker-compose up -d
  args:
    chdir: /home/{{userName}}/docker/rtorrent
