samba:
  image: joebiellik/samba-server
  volumes:
    # You must provide a Samba config file
    - ./smb.conf:/config/smb.conf
    # Shares
    - /home/libesz/downloads:/share
  ports:
    - "137:137/udp"
    - "138:138/udp"
    - "139:139/tcp"
    - "445:445/tcp"
  restart: always
  container_name: samba
  environment:
    #- USERNAME=joe
    #- PASSWORD=samba
    # Defaults
    - UID=1000
    - GID=1000
    - GROUP=samba
    - CONFIG=/config/smb.conf
