- name: Create samba docker-compose directory
  file: path=~/docker/samba state=directory

- name: Copy samba config
  copy: src=smb.conf dest=~/docker/samba/

- name: Create docker compose project
  template: src=docker-compose.yml.j2 dest=~/docker/samba/docker-compose.yml

- name: Create samba service
  docker_service:
    project_src: docker/samba
