- name: Create samba docker-compose directory
  file: path=~/docker/samba state=directory

- name: Copy samba config
  copy: src=smb.conf dest=~/docker/samba/

- name: Create docker compose project
  template: src=docker-compose.yml.j2 dest=~/docker/samba/docker-compose.yml

- name: Create share directory {{sambaWebShareLocation}}
  file: path=~/docker/samba state=directory

- name: Create samba share directories
  become: yes
  action: file path={{item}} state=directory owner={{userName}}
  with_items:
    - "{{downloadLocation}}"
    - "{{sambaWebShareLocation}}"
    - "{{sambaUtilShareLocation}}"
    - "{{sambaPicturesShareLocation}}"
    - "{{sambaOtherShareLocation}}"

- name: Create samba service
  command: docker-compose up -d
  args:
    chdir: docker/samba

