
- name: Install apcupsd daemon
  become: yes
  action: apt pkg=apcupsd state=present update_cache=true

- name: Create APC udev rule
  become: yes
  template: src=20-ups.rules.j2 dest=/etc/udev/rules.d/20-ups.rules mode=0755 owner=root
  register: udevRuleChanged

- name: Ask udev to rename the ups device
  become: yes
  when: udevRuleChanged is changed
  command: udevadm control --reload-rules && udevadm trigger

- name: Create common APC script
  become: yes
  template: src=ups_slack_event.sh.j2 dest=/sbin/ups_slack_event.sh mode=0500 owner=root

- name: Create symbolic links for UPS actions
  become: yes
  file:
    src: "/sbin/ups_slack_event.sh"
    dest: "/etc/apcupsd/{{item}}"
    state: link
    force: yes
  with_items:
  - "powerout"
  - "onbattery"
  - "offbattery"
  - "failing"
  - "timeout"
  - "loadlimit"
  - "runlimit"
  - "doreboot"
  - "doshutdown"
  - "annoyme"
  - "emergency"
  - "changeme"
  - "remotedown"
  - "startselftest"
  - "endselftest"
  - "battdetach"
  - "battattach"

- name: Start apcupsd service
  become: yes
  service: name=apcupsd.service state=started enabled=yes
