- name: Daemon reload
  become: yes
  notify: Start router
  command: systemctl daemon-reload

- name: Start router
  become: yes
  service: name=router state=restarted

- name: Restart dnsmasq
  become: yes
  service: name=dnsmasq state=restarted
