- name: Install basic backages
  become: yes
  apt:
    pkg: ['vim', 'htop', 'aptitude', 'mc', 'git', 'zsh']
    state: present
    update_cache: true

- name: Apply .vimrc
  become_user: "{{userName}}"
  copy: dest=~/.vimrc src=.vimrc owner={{userName}} group={{userName}}

- name: Change shell to zsh
  become: yes
  register: shellChanged
  user: name={{userName}} shell=/bin/zsh

- name: Configure git email
  become_user: "{{userName}}"
  git_config: name=user.email value={{userEmail}} scope=global

- name: Configure git user
  become_user: "{{userName}}"
  git_config: name=user.name value={{userName}} scope=global

- name: Configure git colors
  become_user: "{{userName}}"
  git_config: name=color.ui value=auto scope=global

- name: Kill open ssh sessions
  shell: sleep 1; pkill -u {{userName}} sshd
  async: 3
  poll: 2
  when: shellChanged is changed
  failed_when: false

- name: Get oh-my-zsh
  become_user: "{{userName}}"
  when: shellChanged is changed
  shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: Link zsh settings for root
  become: yes
  action: file src=/home/libesz/{{item}} dest=/root/{{item}} state=link
  with_items:
    - '.oh-my-zsh'
    - '.zshrc'
