- name: Install basic backages
  become: yes
  apt:
    pkg: ['vim', 'htop', 'aptitude', 'mc', 'git', 'zsh', 'python-setuptools', 'python-pip']
    state: present
    update_cache: true

- name: Apply .vimrc
  copy: dest=/home/{{userName}}/.vimrc src=.vimrc owner={{userName}} group={{userName}}

- name: Change shell to zsh
  become: yes
  register: shellChanged
  user: name={{userName}} shell=/bin/zsh

- name: Configure git email
  become_user: "{{userName}}"
  git_config: name=user.email value={{userEmail}} scope=global

- name: Configure git user
  become_user: "{{userName}}"
  git_config: name=user.name value={{userName}} scope=global

- name: Configure git colors
  become_user: "{{userName}}"
  git_config: name=color.ui value=auto scope=global
