- name: Create minidlna docker-compose directory
  file: path=/home/{{userName}}/docker/minidlna state=directory

- name: Create minidlna config
  template: src=minidlna.conf.j2 dest=/home/{{userName}}/docker/minidlna/minidlna.conf

- name: Create minidlna docker-compose yml
  template: src=docker-compose.yml.j2 dest=/home/{{userName}}/docker/minidlna/docker-compose.yml

- name: Increase inotify sysctl
  become: yes
  sysctl: name=fs.inotify.max_user_watches value=100000 sysctl_set=yes state=present reload=yes

- name: Create minidlna service
  command: docker-compose up -d
  args:
    chdir: docker/minidlna

