- name: Install pppoe
  become: yes
  apt: pkg=pppoe state=installed

- name: Configure pppoe peer file
  become: yes
  template: src=dsl-provider-peer.j2 dest=/etc/ppp/peers/dsl-provider

- name: Configure pppoe password in secret files
  become: yes
  action: lineinfile dest={{item}} line="\"{{pppoeUserName}}\" * \"{{pppoePassword}}\""
  with_items:
    - /etc/ppp/chap-secrets
    - /etc/ppp/pap-secrets

- name: Configure dsl-provider in the interfaces file
  become: yes
  template: src=dsl-provider-interface.j2 dest=/etc/network/interfaces.d/dsl-provider

- name: Delete wan interface from the common interface file
  become: yes
  action: lineinfile dest=/etc/network/interfaces state=absent regexp={{item}} backup=yes
  with_items:
    - '{{wanRealNicName}}'
    - 'address'
    - 'netmask'
    - 'broadcast'

- name: Configure manual wan interface
  become: yes
  template: src=wan-interface.j2 dest=/etc/network/interfaces.d/{{wanRealNicName}}

- name: Call pon
  become: yes
  #notify: Reload networking
  command: pon dsl-provider
