- name: Configure static wan interface with static address
  become: yes
  template: src=wan-interface.j2 dest=/etc/network/interfaces.d/{{wanNicName}}

- name: Delete lan interface from the common interface file
  become: yes
  lineinfile: dest=/etc/network/interfaces state=absent regexp='{{lanNicName}}' backup=yes

- name: Configure lan interface with static address
  become: yes
  template: src=lan-interface.j2 dest=/etc/network/interfaces.d/{{lanNicName}}

- name: Create VLAN interfaces
  become: yes
  template: src=vlan-interface.j2 dest=/etc/network/interfaces.d/{{lanNicName}}.{{item.value.vlanId}}
  with_dict: "{{vlans}}"

- name: Bring up VLAN interfaces
  become: yes
  command: ifup {{lanNicName}}.{{item.value.vlanId}}
  with_dict: "{{vlans}}"

- name: Install dnsmasq
  become: yes
  apt: pkg=dnsmasq state=present

- name: Configure dnsmasq for dhcp
  become: yes
  notify: Restart dnsmasq
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf

- name: Copy router/firewall script
  become: yes
  template: src=router.sh.j2 dest=/sbin/router.sh mode=0700 owner=root

- name: Copy router/firewall systemd service file
  become: yes
  notify: Daemon reload
  copy: src=router.service dest=/etc/systemd/system/router.service owner=root

- name: Enable router
  become: yes
  service: name=router enabled=true
