- name: Install docker related packages from official repo
  become: yes
  action: apt pkg={{item}} state=installed update_cache=true
  with_items:
   - apt-transport-https
   - ca-certificates
   - python-pip

- name: Add key for docker apt repo
  become: yes
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker apt repo
  become: yes
  copy: dest=/etc/apt/sources.list.d/docker.list src=docker.list

- name: Install docker packages from docker repo
  become: yes
  action: apt pkg={{item}} state=installed update_cache=true
  with_items:
   - docker-engine

- name: Add user to docker group
  become: yes
  user: name={{userName}} groups=docker
  register: userAddedToDockerGroup

- name: Kill open ssh sessions
  shell: sleep 1; pkill -u {{userName}} sshd
  async: 3
  poll: 2
  when: userAddedToDockerGroup|changed
  failed_when: false

- name: Install docker pip module
  pip: name=docker

- name: Start docker service
  become: yes
  service: name=docker.service state=started

- name: Start docker socket
  become: yes
  service: name=docker.socket state=started
