- name: Install docker related packages from official repo
  become: yes
  apt:
   pkg: ['apt-transport-https', 'ca-certificates', 'gnupg2', 'software-properties-common']
   state: present
   update_cache: true

- name: convert gpg
  shell: "{{ item }}"
  with_items:
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - gpg -a --export 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 | sudo apt-key add -

- name: Add docker apt repo
  become: yes
  copy: dest=/etc/apt/sources.list.d/docker.list src=docker.list

- name: Install docker packages from docker repo
  become: yes
  apt:
    pkg: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
    update_cache: true

- name: Add user to docker group
  become: yes
  user: name={{userName}} groups=docker
  register: userAddedToDockerGroup

- name: Kill open ssh sessions
  shell: sleep 1; pkill -u {{userName}} sshd
  async: 3
  poll: 2
  when: userAddedToDockerGroup is changed
  failed_when: false

- name: Install docker pip modules
  pip: name=["docker", "docker-compose"]
  become: yes

- name: Copy docker daemon settings
  become: yes
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: Start docker service
  become: yes
  service: name=docker.service state=started

- name: Start docker socket
  become: yes
  service: name=docker.socket state=started

- name: Create web backend network
  shell: docker network create web